### ISSUE TITLE
about sc id

### ISSUE THREAD

**Issue by yapcheahshen** [suttacentral/suttacentral-data#1]
SC version split pi/su/dn/dn1.html into 218 paragraphs, why en/pi/su/dn/dn1.html is still using the bps numbering (149 paragraphs?)

**Comment by sujato** [comment]
Our texts come from different sources, and we haven't reconciled the different systems. 

Once we have introduced the next generation of translations, starting with English, this will include consistently tagged text at a sentence or sub-sentence level, while continuing to support legacy references. 

However the only way to get existing texts to agree is to edit them all by hand. 

We have, in fact, done this with the Pali text for DN and MN, which now support the paragraph/section numbers as used in the PTS and subsequent editions (including Wisdom) for the DN, and the Wisdom edition for MN. These paragraph numbers are used fairly widely in the translations, but by no means universally.
